### ISSUE TITLE
Button to reset all active column-based filters

### ISSUE THREAD

**Issue by eimrek** [materialscloud-org/mc-react-ptable-materials-grid#2]
A user might filter based on multiple columns but then want to go back to a state without filters. Currently, they need to click the "Reset" button for each of the applied filters, but it might be good if there was a separate button to reset all the column fitlers. It probably should be somewhere near the head of the table, e.g. next to the hint button.

**Comment by SharanRP** [comment]
@eimrek I have opened the PR which implements this feature
