### ISSUE TITLE
Button to download all filtered materials

### ISSUE THREAD

**Issue by eimrek** [materialscloud-org/mc-react-ptable-materials-grid#3]
The obvious solution would be to go through the aiida rest api for each individual structure but this might be too slow and inefficient. It might be better to save all of the cif files separately in the mcloud API and select correct ones + zip them in the backend. This might be implemented mainly outside of this component, however, there should be easy access to all of the filtered materials ids from this component.

**Comment by SharanRP** [comment]
Hello @eimrek, would you kindly provide additional elaboration on the specific implementation details required?

**Comment by SharanRP** [comment]
I’ve opened a pull request, @eimrek. Could you please take a moment to review it?
